### ISSUE TITLE
Disable home moves

### ISSUE THREAD

**Issue by tsipa** [kfmut/grbl_3x_pmill_post#1]
By a chance do you know how to disable g28 moves? I certainly don't want them.

**Comment by kfmut** [comment]
Если не напрягает, что "голова" станка не будет подниматься по Z перед первым перемещением по XY, то можно просто закомментировать/удалить несколько линий из поста. Перед применением визуально проверить g-code обязательно :-) 

>131 ->   N ; G4  28 ; G5 91 ; Z 0 ; Z =C
>...
>140 ->    N ; G4  28 ; G5 91 ; Z 0 ; G4 =C ; G5 =C ; Z =C
>141 ->    N ; G4  28 ; G5 91 ; X 0 ; Y 0 ; G4 =C ; G5 =C ; X =C ; Y =C

При этом надо чётко следить, чтобы станок не обломил инструмент при самом первом перемещении об заготовку, приспособы и т.д, т.е. типа обнулили Z по столу и сразу нажали "Поехали!". Возможно, что можно сделать, чтобы был первый подъём до безопасной высоты, но навскидку я этого не вспомню.

**Comment by tsipa** [comment]
Amazing! Thank you, comrade. Really appreciate your assistance.

**Comment by kfmut** [comment]
@tsipa 

Посмотрел документацию, 131-ую строчку поста вроде можно так записать для подъёма головы на безопасную высоту:

вместо
> N ; G4 28 ; G5 91 ; Z 0 ; Z =C

должно быть

> N ; G1 0 ; G5 90 ; Z SafeZ ; Z =C

Опять же проверяем на работоспособность до запуска программы на станке, а потом в станке без режущего инструмента, по воздуху.
